esphome:
  name: medienschrank-lufter
  friendly_name: Medienschrank

# inspired by https://github.com/patrickcollins12/esphome-fan-controller/blob/master/console-fan.yaml

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Throttle writing parameters to the internal flash memory to reduce ESP memory wear / degradation
preferences:
  flash_write_interval: 15min


# Reduce log noise
logger:
  level: WARN

# Enable Home Assistant API
api:
  encryption:
    key: "x"

ota:
  - platform: esphome
    password: "x"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Medienschrank-Lufter"
    password: "x"

captive_portal:
    
#####


number:
  # PID Tuning Parameters
  # KP (Proportional) - How aggressively fan responds to temperature changes
  - platform: template
    name: "Response Speed (P)"
    id: kp
    icon: mdi:rabbit
    restore_value: true
    initial_value: 0.3  # Gentle & quiet operation
    min_value: 0.1
    max_value: 1.0
    step: 0.05
    entity_category: config
    mode: box
    set_action:
      lambda: |-
        id(console_thermostat).set_kp( x );

  # KI (Integral) - Corrects long-term temperature drift
  - platform: template
    name: "Drift Correction (I)"
    id: ki
    icon: mdi:target
    restore_value: true
    initial_value: 0.0015  # Slow but stable correction
    min_value: 0
    max_value: 0.005
    step: 0.0001
    entity_category: config
    mode: box
    set_action:
      lambda: id(console_thermostat).set_ki( x );

  # KD (Derivative) - Usually 0 for fan control to avoid noise
  # Uncomment if you experience oscillation and want to experiment
  # - platform: template
  #   name: "Overshoot Prevention (D)"
  #   id: kd
  #   icon: mdi:waves
  #   restore_value: true
  #   initial_value: 0.0
  #   min_value: 0
  #   max_value: 0.1
  #   step: 0.01
  #   entity_category: config
  #   set_action:
  #     lambda: id(console_thermostat).set_kd( x );

  # Advanced deadband settings - uncomment only if needed
  # These are already optimized for quiet operation
  # - platform: template
  #   name: Deadband Threshold Low
  #   ... (defaults: -1.0°C)
  # - platform: template
  #   name: Deadband Threshold High
  #   ... (defaults: 0.4°C)

# IP Address and uptime are available in ESPHome device info page

sensor:
  # WiFi Signal (useful for troubleshooting)
  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 60s
    entity_category: diagnostic

  # Fan RPM from Tachometer
  # See instructions here: https://esphome.io/components/sensor/pulse_counter.html
  - platform: pulse_counter
    pin: 
      number: GPIO21   # Connect to any input PIN on the ESP
      mode: INPUT_PULLUP
    unit_of_measurement: 'RPM'
    id: fan_speed
    name: Fan RPM
    update_interval: 1s # Set to 1 second reporting interval
    accuracy_decimals: 0
    filters:
      - multiply: 0.5  # Depending on how many pulses the fan sends per round - should be 0.5 or 1 - try...


  # Temperature & Humidity Sensor
  - platform: dht
    pin: GPIO0
    model: DHT22
    temperature:
      name: "Temperature"
      id: console_fan_temperature
      accuracy_decimals: 3

      # If you don't smooth the temperature readings 
      # the PID controller over reacts to small changes.
      filters:
         - exponential_moving_average:  
             alpha: 0.1
             send_every: 1

    humidity:
      name: "Humidity"
      id: console_fan_humidity

    # the DHT11 can only be read every 1s. Use 1.3s to be safe.
    update_interval: 1.3s

  # Current fan power level (updated by proxy_output)
  - platform: template
    name: "Current Fan Power"
    unit_of_measurement: "%"
    id: fan_speed_pwm_voltage
    icon: mdi:gauge
    
output:
  # PWM Fan Control (GPIO20 - FIXED, DO NOT CHANGE)
  - platform: ledc
    id: console_fan_speed
    pin: GPIO20  # FIXED - PCB hardware pin
    frequency: "25000 Hz"  # Standard PC fan PWM frequency
    min_power: 10%   # Most fans stall below this
    max_power: 100%
    zero_means_zero: true  # Completely stop fan at 0%

  # PID output with deadband logic
  - platform: template
    id: proxy_output
    type: float
    write_action:
      lambda: |-
        // Only run fan if not in deadband (near target temp)
        float write_val = id(console_thermostat).in_deadband() ? 0.0 : state;
        id(console_fan_speed).set_level(write_val);
        id(fan_speed_pwm_voltage).publish_state(write_val * 100.0);

# PID Temperature Controller
climate:
  - platform: pid
    name: "Temperature Control"
    id: console_thermostat
    sensor: console_fan_temperature
    default_target_temperature: 30°C  # Good for electronics cooling
    cool_output: proxy_output

    # Temperature range in Home Assistant UI
    visual:
      min_temperature: 0°C   # Set to 0°C for "always run at 100%" mode
      max_temperature: 45°C  # Reasonable max for electronics

    # PID Parameters (tuned for quiet operation)
    control_parameters:
      kp: 0.3      # Gentle response (set by Response Speed slider)
      ki: 0.0015   # Slow drift correction (set by Drift Correction slider)
      kd: 0        # No derivative (causes noise in fan systems)
      max_integral: 0.0  # Prevent integral windup

    # Deadband - prevents oscillation near target temp
    deadband_parameters:
      threshold_high: 0.4°C   # Stop fan when 0.4°C below target
      threshold_low: -1.0°C   # Start fan when 1.0°C above target
      ki_multiplier: 0.04     # Gentle integral in deadband

switch:
  # Restart button (if needed)
  - platform: restart
    name: "Restart"
    entity_category: config

button:
  # Auto-tune PID (warning: optimizes for accuracy, not quiet operation)
  - platform: template
    name: "Auto-Tune PID"
    entity_category: config
    on_press:
      - climate.pid.autotune: console_thermostat
